type: object
title: Config Object Rule
description: Format of Config Hub Object Rules
properties:
  path:
    type: string
    description: JSONPath expression denoting the path within the object where a value substitution should be applied
    example: $.enabled
  value:
    type: object
    description: Value to be assigned at the jsonPath location within the object
    nullable: true
    example: null
  mode:
    type: array
    description: Draft modes to which this rule will apply
    items:
      type: string
      enum:
        - RESTORE
        - PROMOTE
        - UPLOAD
    example: [RESTORE, PROMOTE]